using MIND.Core;
using UnityEngine;

namespace MIND.NPC
{
    /// <summary>
    /// Connects NPC behavior with the conversation system.
    /// Since all dialogue now goes through LLM, this adapter only handles
    /// mapping conversation events to NPC-specific behaviors (if needed).
    /// </summary>
    public class NPCDialogueAdapter : MonoBehaviour
    {
        /// <summary>
        /// Returns PHQ severity label for logging/debugging.
        /// Actual dialogue is generated by LLM — no hardcoded text.
        /// </summary>
        public string GetSeverityLabel(PhqSeverity severity)
        {
            return severity switch
            {
                PhqSeverity.Minimal => "Minimal",
                PhqSeverity.Mild => "Mild",
                PhqSeverity.Moderate => "Moderate",
                PhqSeverity.Severe => "Severe",
                _ => "Unknown"
            };
        }
    }
}
